### ISSUE TITLE
ReactJS templates

### ISSUE THREAD

**Issue by zemlanin** [Prom-ua/PromDocs#4]
Какое решение для реиспользования логики компонента с различными шаблонами?

Мы в команде обычно выносим её миксин и внешний вид меняем отдельными компонентами (например, RComparisonMixin и RComparison/RComparisonStar/RComparisonLabel)

Ещё видел в проекте решения с одним компонентом, в котором есть несколько функция вроде render_x/render_y/render_z, которые вызываются из основного render в зависимости от props компонента

**Comment by AlexMost** [comment]
Дело вкуса. Я за то чтобы в самих компонентах было минимум логики. Понятно что совсем избежать этого нельзя. Я бы пробрасывал view как параметр, и в функции render делал что-то типа

``` coffee
render: ->
    if @props.view
        @props.view data
    else
         # обычный render по default-y
```

В идеале React компонент и должен состоять только из ф-ции render. Но мир не идеален =(
А по поводу миксинов, считаю что они достаточно сложны, и должны использоваться тогда, когда без них никак. А отрисовка view - задача достаточно простая. Как по мне лучше уже продублировать компонент, чем изменять view миксинами.

**Comment by zemlanin** [comment]
Минимум логики — то само собой, но надо же куда-то отправку сообщений в Rx вставлять

Ну, раз дело вкуса, то ок. Если завтра ни у кого не возникнет аргументов по этому поводу, то закрою

**Comment by zemlanin** [comment]
С миксином, в котором только и есть универсальные Rx-хэндлеры, у компонент как раз и остаётся один чистенький `render` с одним DOM-деревом

**Comment by AlexMost** [comment]
не понял что такое универсальный Rx-хендлер) Вынести отправку сообщений в миксин полностью тоже не выйдет, куски все равно будут торчать во view, так лучше уже там несчастный eventStream.onNext вызвать.

**Comment by zemlanin** [comment]
Ну, как раз этот несчастный onNext. Плюс, в миксине удобно прятать
манипуляции со стейтом для всяких попапов и классов типа *_hovered (да-да,
это не pure)

**Comment by AlexMost** [comment]
можно попробовать, нужно на примере глянуть
